### ISSUE TITLE
Module ""@zenfs/core"" has no exported member "resolveBackend"

### ISSUE THREAD

**Issue by QingShan-Xu** [zen-fs/port#4]
Hi, does the readme of @zenfs/port need to be updated? I got the error after following the example.

1. this main.ts
```typescript
import { configure } from '@zenfs/core'
import { Port } from '@zenfs/port'

worker.current = new MyWorker();
await configure({ backend: Port, port: worker.current })
``` 
2. this worker.ts
```typescript
import { resolveBackend } from "@zenfs/core"
import { IndexedDB } from "@zenfs/dom"
import { attachFS } from "@zenfs/port"

const init = async () => {
  const tmpfs = await resolveBackend({ backend: IndexedDB })
  attachFS(self, tmpfs)
}

init()  
``` 

Module ""@zenfs/core"" has no exported member "resolveBackend".

what should i use instead，thanku

**Comment by dr-vortex** [comment]
Thanks!

It should be fixed now. Please let me know if you have any issues.

**Comment by QingShan-Xu** [comment]
The problem still exists, the following code throws this error：

```typescript
await configure({
      '/worker': {
        backend: Port,
        port: worker,
      },
})
``` 

```shell
Error: EPERM: Backend not available: [object Object]
    at Ye (config.js:40:15)
    at async lG (config.js:62:25)
``` 

this is complete code：
```typescript
import { configure, fs } from '@zenfs/core'
import { Port } from '@zenfs/port'
import MyWorker from "./worker?worker&inline"

const worker = new MyWorker()
await configure({
      '/worker': {
        backend: Port,
        port: worker,
      },
})
```

**Comment by dr-vortex** [comment]
@QingShan-Xu This should be resolved in [v0.1.1](https://github.com/zen-fs/port/releases/tag/v0.1.1). Please let me know if you are having any other issues.

I apologize for misunderstanding the original issue, I thought it was an issue with the readme.

**Comment by QingShan-Xu** [comment]
code Unchanged, this new Error :
```typescript
config.js:40 Uncaught (in promise) Error: EPERM: Backend not available: [object Object]
    at cd (config.js:40:15)
    at async $m (config.js:62:25)
    at async e2 (Backend.tsx:14:5)
```

**Comment by dr-vortex** [comment]
@QingShan-Xu,

It looks like there is not a way to check if the backend is available when configure is used. I've removed those checks in [v0.1.2](https://github.com/zen-fs/port/releases/tag/v0.1.2). Please tell me if that fixes the issue.

**Comment by QingShan-Xu** [comment]
The error disappeared.

main's fs is not connected to worker's fs. I don't know what went wrong. Can you help me point out the code problem?

In React and Vite
main.tsx:

Error: ENOENT: No such file or directory, '/test.txt'
```typescript
import { configure, fs } from '@zenfs/core'
import { Port } from '@zenfs/port'
import { useEffect, useRef } from 'react'
import MyWorker from "./worker?worker&inline"

export const Main= () => {
  const worker = useRef(new MyWorker())

  useEffect(() => {
    worker.current.onmessage = async ({ data }) => {
      if (data == "init-success") {
        await configure({
          '/': {
            backend: Port,
            port: worker.current,
          },
        })
        const testFile = await fs.promises.readFile("/test.txt")
        console.log(testFile)
      }
    }
  }, [])


  return (
    <div>Main</div>
  )
}
``` 

worker.ts:

No Error and log successfully.
```typescript
import { InMemory, fs, resolveMountConfig } from '@zenfs/core'
import { attachFS } from '@zenfs/port'

const init = async () => {
  const tmpfs = await resolveMountConfig({ backend: InMemory, name: 'tmp' })
  attachFS(self, tmpfs)
  await fs.promises.writeFile("/test.txt", "test1")
  const testFile = await fs.promises.readFile("/test.txt")
  console.log(testFile)
  postMessage("init-success")
}

init()
```

**Comment by dr-vortex** [comment]
Your worker code should look like this:
```ts
import { InMemory, fs, resolveMountConfig } from '@zenfs/core'
import { attachFS } from '@zenfs/port'

const tmpfs = await resolveMountConfig({ backend: InMemory, name: 'tmp' })
attachFS(self, tmpfs)
await fs.promises.writeFile("/test.txt", "test1")
const testFile = await fs.promises.readFile("/test.txt")
console.log(testFile)
postMessage("init-success")
```

If the error persists, please log all of the worker messages. That should reveal if the issue is in transport or something else.

**Comment by dr-vortex** [comment]
@QingShan-Xu,

Any updates on this?

**Comment by dr-vortex** [comment]
@QingShan-Xu I'm closing this as the original issue as well as your followup should be fixed.
